### PR TITLE
LogoVote : contract deployment on kovan/rinkeby network

### PR DESCRIPTION
**Pull request by y12studio**
Running migrations - Truffle  http://truffle.readthedocs.io/en/beta/getting_started/migrations/

### CODE REVIEW

**Comment by y12studio** [comment]
@willliw @ChihChengLiang 
Ready for review and merge

**Comment by willliw** [comment]
utACK

**Review by ChihChengLiang — APPROVED** [review]
Though I failed to test the kovan migration due to the incompatible parity mnemonic code, the else where looks good.

**Comment by ChihChengLiang** [comment]
Arrr it works! To test the Kovan migration, use the mnemonic code generated by testrpc, and send some Kovan ether to one of the testrpc accounts.

**Comment by y12studio** [comment]
@ChihChengLiang Thank you for parity mnemonic test. I used the mnemonic from the 'Reveal Seed Words' in MetaMask to run truffle migrate.

**Pull request merged**
