### PR TITLE
LogoVote: Add TestLogoVote.sol

### PR DESCRIPTION
**Pull request by y12studio**

### CODE REVIEW

**Comment by ChihChengLiang** [comment]
wow 原來可以把測試寫在 solidity 裡面啊？

**Comment by y12studio** [comment]
也是第一次寫這種。

**Comment by y12studio** [comment]
travis-ci issue ?

fireshot capture 1045 - build 14 - ethertw_smart-contracts -_ - https___travis-ci org_ethertw_sma

**Comment by ChihChengLiang** [comment]
Triggered the rebuild, and it is all good now

**Review by ChihChengLiang — APPROVED** [review]
LGTM

**Pull request merged**
